/* eslint-disable indent */
module.exports = {
    retrieveResponse: function(targetUser) {
        const responseList = [
            'The spanking was successful!',
            `Feel the pain ${targetUser}!!!`,
            `Hahaha, you look like you are enjoying this ${targetUser}.`,
            `Would you prefer for another round? ${targetUser}`,
            `Nothing beats beating other people, would you agree ${targetUser}`,
            'Come get some!!!',
            `You feeling good? ${targetUser}`,
            `Cum! ${targetUser}`,
            'They call me...the spankinator 6900',
            `Words cannot describe how amazing it feels when i spank ${targetUser}, so let me spank you some more.`,
            `I would be happy to spank ${targetUser} for free`,
            `Are you ok? ${targetUser}, let me spank you a little more.`,
            'Oh yea i love SCP, Spank Chosen People',
            'Are you dummy thicc? Yes or no, let me spank em.',
            'Gimme them butt cheeks and lemme spank em.',
            'Choo choo, here comes the spanking train',
            'Are you getting turned on??, let me do it some more.',
            'You know, sometimes I question myself, why do i even spank people, when i can spank myself :(',
            'TARGET ACQUIRED: ACTIVATING SPANKING ABILITIES SET TO 42069% POWER!',
            'A duck walked up to the spanking stand, he asked the man, running the stand, "Hey!" SPANK! SPANK! SPANK! Got any spanks?',
            '*proceeds to spank with horny intent',
            `Forgive me ${targetUser}, but I must go all out`,
            'Sometimes I wonder who even invented the word spank.',
            'Don\'t worry, if someone notices your injuries, just say tis but a scratch.',
            'SKI-BI DIBBY DIB YO DA DUB DUB \n YO DA DUB DUB \n SKI-BI DIBBY DIB YO DA DUB DUB \n YO DA DUB DUB....I\'M THE SPANK MAN',
            `My god! I spanked ${targetUser} until he gone plaid!`,
            'I cum',
            'spankety, spankety, spankety.',
        ];
        const resIndex = Math.floor(Math.random() * responseList.length);
        return responseList[resIndex];
    },

    retrieveGif: function() {
        const gifList = [
            // Total current gifs: 50
            // Anime Gifs
            'https://tenor.com/view/spank-spanking-anime-spank-daisuke-gif-21468457',
            'https://tenor.com/view/bad-beat-spank-punishment-gif-13569259',
            'https://tenor.com/view/anime-school-girl-smack-spanking-spank-gif-19349444',
            'https://tenor.com/view/bad-beat-spank-punishment-gif-13569259',
            'https://tenor.com/view/anime-waifu-spanking-spank-smack-gif-18714058',
            'https://tenor.com/view/anime-salia-tereshkova-cross-ange-spank-blushing-gif-15788982',
            'https://tenor.com/view/anime-waifu-spanking-spank-smack-gif-19431854',
            'https://tenor.com/view/anime-spank-ouch-pain-cry-gif-16173937',
            'https://tenor.com/view/anime-spanking-spank-schoolgirl-naughty-gif-16082139',
            'https://tenor.com/view/bad-spank-cry-anime-gif-15905904',
            'https://tenor.com/view/spank-anime-spank-butt-gif-12325914',
            'https://tenor.com/view/chika-fujiwara-angry-anime-spank-gif-13585603',
            'https://tenor.com/view/anime-girl-spank-animegirl-spanking-gif-15964704',
            'https://tenor.com/view/anime-spank-giyu-tomioka-shinobu-kocho-giyu-spank-tomioka-spank-gif-17299734',
            'https://tenor.com/view/tom-and-jerry-anime-spank-gif-11756736',
            'https://tenor.com/view/anime-spank-sailor-moon-chibiusa-gif-16910479',
            'https://tenor.com/view/spank-spanking-anime-badchildrin-daughter-gif-9772233',
            'https://tenor.com/view/anime-asobi-asobase-spank-gif-21443761',
            'https://tenor.com/view/spank-anime-spanked-spanking-dr-gif-9583397',
            'https://tenor.com/view/anime-love-spank-spank-head-chop-gif-12606592',
            'https://tenor.com/view/anime-spoiled-kids-spank-sister-gif-7922491',
            'https://tenor.com/view/anime-schoolgirl-spank-spanking-smack-gif-16055441',
            'https://tenor.com/view/gintama-anime-seesaw-spank-costume-gif-7885617',
            'https://tenor.com/view/onizuka-spank-spanking-angry-anime-gif-5458569',
            'https://tenor.com/view/anime-spanking-spank-naughty-girl-punishment-gif-18105116',
            'https://tenor.com/view/ueno-anime-waifu-school-girl-spanking-gif-21371415',
            'https://tenor.com/view/anime-school-girl-spanking-naughty-spank-gif-16224449',
            'https://tenor.com/view/spank-whip-hurt-gif-15492223',
            'https://tenor.com/view/spank-bad-smack-fire-gif-15492222',
            'https://tenor.com/view/spank-peach-spanking-gif-15659527',
            'https://tenor.com/view/pinch-%d5%bd%d5%a5%d6%80-spank-mad-gif-16162241',
            'https://tenor.com/view/anime-kobayashi-kanna-beach-watermelon-gif-21452149',
            'https://tenor.com/view/no-angry-anime-slap-gif-7355956',
            'https://tenor.com/view/anime-slap-gif-10426943',
            'https://tenor.com/view/konosuba-gif-7864657',
            'https://tenor.com/view/anime-lewd-anime-lewd-slap-gif-20060132',
            'https://tenor.com/view/mio-isurugi-mm-anime-slap-gif-16250277',
            'https://tenor.com/view/oreimo-gif-10937029',
            'https://tenor.com/view/konosuba-witch-anime-slap-angry-gif-8065158',
            'https://tenor.com/view/ass-pain-maou-sama-retry-gif-20927289',
            'https://tenor.com/view/anime-slap-girl-boy-gif-7919028',
            'https://tenor.com/view/anime-slap-cute-dog-gif-13642334',
            'https://tenor.com/view/anime-slap-bitchslap-gif-18965728',
            'https://tenor.com/view/butt-slap-hunter-xhunter-anime-slap-ouch-gif-12178033',
            'https://tenor.com/view/rosario-vampire-anime-slap-butt-gif-3412059',
            // non Anime
            'https://tenor.com/view/spank-gif-18811244',
            'https://tenor.com/view/spank-gif-9146507',
            'https://tenor.com/view/spank-tinkerbell-gif-8853370',
            'https://tenor.com/view/spank-pig-food-gif-14140813',
            'https://tenor.com/view/villain-catwoman-whip-gif-5262076',
            'https://tenor.com/view/funny-spank-hit-gif-13215952',
        ];
        const gifIndex = Math.floor(Math.random() * gifList.length);
        return gifList[gifIndex];
    },
};